### ISSUE TITLE
Some question about principle

### ISSUE THREAD

**Issue by ktxu1224** [tkwoo/StereoVisionforADAS#2]
Hi, I am still a little puzzed by the principle of this project, so can  you give me more instruction for me to modify this algorithm? As I understand, this project does as follow:
1. get the disparity map and remove the ground using V-disparity;
2. set a constant height and uses stixel world to describe the obstacle under the height;
right?
but I don't know the next step stixel segmentation, what this step based on to segment stixel into different objects?  
Can you give me more instruction about this? Thx a lot ! !

**Comment by tkwoo** [comment]
1. good
2. set maximum constant height. stixel's height cannot be over maximum height.

### stixel segmentation
1. choose closest stixel from camera. this stixel is first cluster.
2. check distance between cluster and neighbor stixel. if dist < 2.5m, then add stixel to cluster.
3. iter

**Comment by bjerr** [comment]
Hi,thankyou for your project. I want to know do you have papers for your froject? the CVLAB cannot loin in now
